name: Create and Release N-gram File

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リリース作成のための書き込み権限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # requirements.txtからインストール
          pip install -r requirements.txt

      - name: Download NLTK data
        # ▼▼▼ 'averaged_perceptron_tagger' を追加 ▼▼▼
        run: python -m nltk.downloader punkt words averaged_perceptron_tagger

      - name: Run script to generate n-gram file
        run: python main.py

      # ▼▼▼ このステップを修正 ▼▼▼
      - name: Archive production artifacts
        run: |
          # Pythonスクリプトで定義されたファイル名と一致させる
          ARTIFACT_FILE="1-grams_score_cost_pos_combined.txt"
          # ZIPファイル名を設定
          zip "${ARTIFACT_FILE%.txt}.zip" "$ARTIFACT_FILE"

      # ▼▼▼ 'files' の指定を *.zip に変更 ▼▼▼
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.zip # 生成されたZIPファイルをアップロード
