name: Create and Release N-gram File

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リリース作成のための書き込み権限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ▼▼▼ このステップを修正 ▼▼▼
      # 品詞推定(averaged_perceptron_tagger)とストップワード(stopwords)のデータを追加
      - name: Download NLTK data
        run: python -m nltk.downloader punkt averaged_perceptron_tagger stopwords

      - name: Run script to generate n-gram file
        run: python main.py

      - name: Archive production artifacts
        run: |
          # スクリプトによって動的に生成されたファイル名を取得
          ARTIFACT_FILE=$(ls ./*-grams_score_*_pos_combined.txt)
          zip "${ARTIFACT_FILE%.txt}.zip" "$ARTIFACT_FILE"

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.zip # 生成されたZIPファイルをアップロード
