name: Create and Release N-gram File

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リリース作成のための書き込み権限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ▼▼▼ 修正点: 'words' パッケージもダウンロードする ▼▼▼
      - name: Download NLTK data
        run: python -m nltk.downloader punkt punkt_tab words

      - name: Run script to generate n-gram file
        run: python main.py

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./*-grams_score_*.txt
