name: Build N-gram and Release

on:
  push:
    tags: ['v*.*.*']   # v1.0.0 等で実行

jobs:
  build:
    strategy:
      matrix:
        part: [0, 1, 2, 3]      # ← 並列数。増減させる場合は NUM_PARTS と合わせる
    runs-on: ubuntu-latest
    env:
      NUM_PARTS: 4
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install datasets tqdm spacy numpy
          python -m spacy download en_core_web_sm

      - name: Run worker
        env:
          PART: ${{ matrix.part }}
        run: python worker.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: counts
          path: counts_part${{ matrix.part }}.txt

  merge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write        # Release への書き込み権限
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install merge deps
        run: |
          python -m pip install --upgrade pip numpy

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: counts
          path: .

      - name: Merge & score
        run: python merge.py

      - name: Zip final file
        run: zip ngrams.zip 1-grams_score_cost_pos_combined.txt

      - name: Create Release and upload asset
        uses: softprops/action-gh-release@v2
        with:
          files: ngrams.zip
